main: groupChat.GroupChat
name: GroupChat
version: 1.0.0
description: Group Chat Plugin
api-version: 1.16
Author: Nick V

commands:
  group:
    description: Primary command for the GroupChat plugin
  g:
    description: Speak within a GroupChat group
  confirm:
    description: Confirmation command for the GroupChat plugin
