main: groupChat.GroupChat
name: GroupChat
version: ${project.version}
description: GroupChat - Chat with your friends!
api-version: 1.18
Author: _NickVo

commands:
  group:
    description: Primary command for the plugin
  g:
    description: Speak within a group
  confirm:
    description: Confirmation command for the plugin
